# Generated by Django 5.0.6 on 2024-05-27 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
        ("wagtailcore", "0093_uploadedfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompoundPlan",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("goal_name", models.CharField(max_length=255)),
                (
                    "initial_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "target_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("target_date", models.DateField()),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
